version: '3.1'

services:
  wordpress:
    container_name: wordpress_${SITE}
    image: wordpress
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 80:80
    build:
      context: ${PROJECT_PATH}/docker
      dockerfile: ${PROJECT_PATH}/docker/Dockerfile
    domainname: ${SITE}
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_NAME: ${SITE}_db
      WORDPRESS_DB_USER: ${SITE}_db_user
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db_pass}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-true}
    expose:
      - 9003
    volumes:
      - ${PROJECT_PATH}/docker/config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ${PROJECT_PATH}/docker/config/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ${PROJECT_PATH}/www:/var/www/html

  database:
    container_name: database_${SITE}
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${SITE}_db
      MYSQL_USER: ${SITE}_db_user
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db_pass}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: