#!/bin/bash

PROJECT_PATH=$PWD
DOCKER_COMPOSE_FILE="$PROJECT_PATH/docker/docker-compose.yml"

mkdir $PROJECT_PATH/www 2> /dev/null

if [[ ! -f "$PROJECT_PATH/.env.docker" ]]; then
    echo "Please create an .env.docker file in your project root. See docker/.env.example for options."
    exit 1;
fi

PROJECT_PATH=$PWD docker compose --env-file "$PROJECT_PATH/.env.docker" -f "$DOCKER_COMPOSE_FILE" up -d
